USE [Task_Manager_DB]
GO

/****** Object:  Table [dbo].[COMMENTS]    Script Date: 1.06.2024 17:24:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COMMENTS](
	[COMMENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[TASK_ID] [int] NULL,
	[USER_ID] [int] NULL,
	[COMMENT_TEXT] [nvarchar](max) NULL,
	[COMMENT_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[COMMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[COMMENTS]  WITH CHECK ADD FOREIGN KEY([TASK_ID])
REFERENCES [dbo].[TASKS] ([TASK_ID])
GO

ALTER TABLE [dbo].[COMMENTS]  WITH CHECK ADD FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USERS] ([USER_ID])
GO


