USE [Task_Manager_DB]
GO

/****** Object:  Table [dbo].[TASKS]    Script Date: 1.06.2024 17:25:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TASKS](
	[TASK_ID] [int] IDENTITY(1,1) NOT NULL,
	[TITLE] [nvarchar](100) NULL,
	[DESCRIPTION] [nvarchar](255) NULL,
	[IS_COMPLETED] [bit] NULL,
	[DUE_DATE] [datetime] NULL,
	[REMINDER_TIME] [int] NULL,
	[LOGIN_ID] [int] NULL,
	[PRIORITY] [int] NOT NULL,
	[TAGS] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[TASK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TASKS] ADD  CONSTRAINT [DF_TASKS_DUE_DATE]  DEFAULT (getdate()) FOR [DUE_DATE]
GO

ALTER TABLE [dbo].[TASKS] ADD  DEFAULT ((0)) FOR [PRIORITY]
GO


