USE [Task_Manager_DB]
GO

/****** Object:  Table [dbo].[TASK_SHARES]    Script Date: 1.06.2024 17:25:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TASK_SHARES](
	[SHARED_ID] [int] IDENTITY(1,1) NOT NULL,
	[TASK_ID] [int] NULL,
	[SHARED_WITH_USER_ID] [int] NULL,
 CONSTRAINT [PK_TASK_SHARES] PRIMARY KEY CLUSTERED 
(
	[SHARED_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TASK_SHARES]  WITH CHECK ADD  CONSTRAINT [FK__TASK_SHAR__SHARE__29572725] FOREIGN KEY([SHARED_WITH_USER_ID])
REFERENCES [dbo].[USERS] ([USER_ID])
GO

ALTER TABLE [dbo].[TASK_SHARES] CHECK CONSTRAINT [FK__TASK_SHAR__SHARE__29572725]
GO

ALTER TABLE [dbo].[TASK_SHARES]  WITH CHECK ADD  CONSTRAINT [FK__TASK_SHAR__TASK___286302EC] FOREIGN KEY([TASK_ID])
REFERENCES [dbo].[TASKS] ([TASK_ID])
GO

ALTER TABLE [dbo].[TASK_SHARES] CHECK CONSTRAINT [FK__TASK_SHAR__TASK___286302EC]
GO


