USE [Task_Manager_DB]
GO

/****** Object:  Table [dbo].[USERS]    Script Date: 1.06.2024 17:26:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USERS](
	[USER_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_NAME] [nvarchar](100) NULL,
	[USER_SURNAME] [nvarchar](100) NULL,
	[USER_ADRESS] [nvarchar](255) NULL,
	[TC_IDENTITY] [nvarchar](11) NULL,
	[IS_STATUS] [bit] NULL,
	[IS_ADMIN] [bit] NULL,
	[PASSWORD] [nvarchar](255) NULL,
	[PHONE_NUMBER] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


